# Generated by Django 3.2.11 on 2022-08-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=20, verbose_name='twitter handle'),
        ),
    ]
